Resources: 
  MyInstance:
    Type: AWS::EC2::Instance 
    Properties:
      InstanceType: t2.micro
      ImageId: ami-04b70fa74e45c3917
      Tags:
        - Key: "Name"
          Value: !Join ["-",[my,virtual,server]]
