Resources: 
  MyInstance:
    Type: AWS::EC2::Instance 
    Properties:
      InstanceType: t2.micro
      ImageId: ami-04b70fa74e45c3917
      Tags:
        - Key: "Name"
          Value: !Join
            - " "
            - - "My instance is in"
              - !Ref AWS::Region
      SecurityGroups:
        - !Ref StackSG

  StackSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http & ssh from MyIP
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      Tags:
        - Key: "Name"
          Value: "Stack-SG"